version: '3'

services:
  secret_did_moroz_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secret_did_moroz_bot
    env_file: .env
    volumes:
      - ./src:/app
    restart: always
